__int64 __fastcall wlan_create_subelem_fragseq(
        char a1,
        char a2,
        char a3,
        _BYTE *a4,
        unsigned __int64 a5,
        unsigned __int64 a6,
        _BYTE *a7,
        unsigned __int64 a8,
        double a9,
        double a10,
        double a11,
        double a12,
        double a13,
        double a14,
        double a15,
        double a16,
        unsigned __int64 *a17)
{
  return wlan_create_elemsubelem_fragseq(
           a1,
           1,
           a2,
           0,
           a3,
           a4,
           a5,
           a6,
           a9,
           a10,
           a11,
           a12,
           a13,
           a14,
           a15,
           a16,
           a7,
           a8,
           a17);
}
